# Generated by Django 3.1.7 on 2021-05-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discodecurso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacurso',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
    ]
