# Generated by Django 3.1.7 on 2021-05-05 21:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discodecurso', '0002_auto_20210505_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Tema')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('estado', models.BooleanField(default=True, verbose_name='Visible/No Visible')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discodecurso.curso')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Lección')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido del Tema')),
                ('codigo', ckeditor.fields.RichTextField(verbose_name='Codigo')),
                ('estado', models.BooleanField(default=True, verbose_name='Visible/No Visible')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discodecurso.tema')),
            ],
            options={
                'verbose_name': 'leccion',
                'verbose_name_plural': 'lecciones',
            },
        ),
    ]
