# Generated by Django 3.1.7 on 2021-05-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discodecurso', '0003_leccion_tema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leccion',
            old_name='slug',
            new_name='slug_leccion',
        ),
        migrations.RenameField(
            model_name='tema',
            old_name='slug',
            new_name='slug_tema',
        ),
    ]
