# Generated by Django 3.1.7 on 2021-05-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discodecurso', '0004_auto_20210505_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leccion',
            old_name='slug_leccion',
            new_name='slugleccion',
        ),
        migrations.RenameField(
            model_name='tema',
            old_name='slug_tema',
            new_name='slugtema',
        ),
    ]
