# Generated by Django 3.1.7 on 2021-05-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discodecurso', '0006_auto_20210505_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='slug',
        ),
    ]
