# Generated by Django 3.1.7 on 2021-05-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discodecurso', '0007_auto_20210506_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='codigo',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Codigo'),
        ),
    ]
