# Generated by Django 3.1.7 on 2021-05-06 04:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discodecurso', '0008_auto_20210506_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='codigo',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
