# Generated by Django 3.1.7 on 2021-05-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discodecurso', '0009_auto_20210506_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='codigo',
            field=models.TextField(verbose_name='Codigo'),
        ),
    ]
