# Generated by Django 3.1.7 on 2021-05-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discodecurso', '0010_auto_20210506_0450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
    ]
