# Generated by Django 3.1.7 on 2021-05-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discodesocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo/No Activo'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo/No Activo'),
        ),
    ]
