# Generated by Django 3.1.7 on 2021-05-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoderetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='descripcion',
            field=models.CharField(default=1, max_length=100, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
