# Generated by Django 3.1.7 on 2021-05-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discoderetos', '0003_auto_20210505_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'challenge', 'verbose_name_plural': 'challenges'},
        ),
    ]
