# Generated by Django 3.1.7 on 2021-04-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discodeapp', '0003_auto_20210425_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(max_length=510),
        ),
    ]
