# Generated by Django 3.1.7 on 2021-04-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discodeapp', '0004_auto_20210425_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
    ]
