# Generated by Django 3.1.7 on 2021-05-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discodeapp', '0005_auto_20210425_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(blank=True, max_length=700, null=True, verbose_name='Keywords'),
        ),
    ]
