# Generated by Django 3.1.7 on 2021-05-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discodeapp', '0006_post_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Palabras Clave (500 Carácteres)'),
        ),
    ]
