# Generated by Django 3.1.7 on 2021-05-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discodeapp', '0008_categoriafaq_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaFAQ',
        ),
        migrations.DeleteModel(
            name='Faqs',
        ),
    ]
