# Generated by Django 3.1.7 on 2021-05-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discodeapp', '0009_auto_20210504_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
